#ifndef CONSOLE_BLACKJACK_GAME_H
#define CONSOLE_BLACKJACK_GAME_H
#include "includes.h"
#include "deck.h"
void blackjack();
bool getBool();
int askIfContinue();
int getInt();
#endif //CONSOLE_BLACKJACK_GAME_H
